apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: tikops/flask:latest
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/mysql/ssl
        ports:
        - containerPort: 5000
      volumes:
      - name: ssl-certs
        configMap:
          name: mysql-ssl-certs
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
