apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-executor
subjects:
- kind: ServiceAccount
  name: pod-executor
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-executor
  apiGroup: rbac.authorization.k8s.io
