apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-backup-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-backup-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: mysql-backup-role
  apiGroup: rbac.authorization.k8s.io
